# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a915b0b84e01c608c5cf9d8e9627553bbbc0364efe6c3e2b3867409de9bf9e088e293db5371f63490277a8d0ee166018c75063adcb6d8d495c36e7505b1de79

test:
  secret_key_base: 9a843e0efbe8827f3440c275e963cdacdfb36d663140b03d1daf74f860ec6e69c524aa492bce5bb60b8e0a5b1c249849b3a4df2f1000ccb3ba0aab89655cba79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
